version: "3.3"
services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu
    restart: always
    volumes:
      - ./app:/app
    ports:
      - "8080:80"
    command: apache2ctl -D FOREGROUND
