version: "3.3"
services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu
    restart: always
    volumes:
      - ./app:/app
    network_mode: host
    command: apache2ctl -D FOREGROUND